version: "3"
services:

  zookeeper:
    image: bitnami/zookeeper:3-ol-7
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi:
    image: apache/nifi:1.9.2
    ports:
      - 8080
    depends_on:
      - zookeeper
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: success_data:1:1,compact_data:1:1,failure_data:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  log-generator:
    build:
      context: .
      dockerfile: ./log-generator/Dockerfile
        
    # image: mingrammer/flog:0.3.1
    # command: flog -w -t log -n 20000 -o /var/log/flink.log
